core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('onenlp_app.urls')),
    path('admin/', admin.site.urls),
]

onenlp_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib import admin

admin.autodiscover()
admin.site.login = login_required(admin.site.login)


app_name = 'onenlp_app'


urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", include("social_django.urls", namespace='social')),

    path('', views.HomeView.as_view(), name='home'),
    path("logout", views.Logout.as_view(), name = 'logout'),
    path("dashboard", views.Dashboard.as_view(), name= 'dashboard'),



    path('update', views.Update.as_view(), name = 'update'),
    path('delete', views.Delete.as_view(), name = 'delete'),
    path('api/segment', views.Segmentor.as_view(), name='segmentor'),
    path('api/summary', views.Summary.as_view(), name="summary"),
    path('api/sentencer', views.Sentencer.as_view(), name="sentencer"),
    path('api/dependency', views.Dependency.as_view(), name="dependency"),
    path('api/sentiment', views.Sentiment_Analysis.as_view(), name="sentiment"),
    path('api/phraseMatcher', views.PhraseMatcher.as_view(), name="phraseMatcher"),
    path('api/opposite', views.OppositeWord.as_view(), name="opposite"),
    path('api/usage', views.UsageOfWord.as_view(), name="usage"),
    path('aboutus', views.Aboutus.as_view(), name="aboutus"),

]

auth0login/models.py
from django.db import models

# Create your models here.

onenlp_app/models.py
from django.db import models

# Create our models here.
class TimeAuditModel(models.Model):
    """ To path when the record was created and last modified """
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created At",)
    updated = models.DateTimeField(auto_now=True, verbose_name="Last Modified At")

    class Meta:
        abstract = True

class Snippets(TimeAuditModel):
    title = models.CharField(max_length=255, unique=True)
    content = models.TextField(blank=True, default="")
    author = models.CharField(max_length=255, null=True, blank = True)

    class Meta:
        db_table = "snippets"
        ordering = ["-created"]

    def __str__(self):
        return self.title

auth0login/views.py
from django.shortcuts import render

# Create your views here.

onenlp_app/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404
)
from django.views import View
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.views.generic import FormView
from django.urls import reverse
import json 
from urllib.parse import urlencode
from .onenlp import OneNLP
from core.settings import LOGIN_URL
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as log_out
from .models import Snippets




class HomeView(View):
    def get(self, request):
        context = {}
        if request.GET.get('title'):
            context['title'] = request.GET.get('title')
            context['content'] = request.GET.get('content')

        context['login_url'] = LOGIN_URL
        return render(request, 'home.html', context)


class Logout(View):
    def get(self, request):
        log_out(request)
        return_to = urlencode({"returnTo": request.build_absolute_uri("/")})
        logout_url = "https://{}/v2/logout?client_id={}&{}".format(
            settings.SOCIAL_AUTH_AUTH0_DOMAIN, settings.SOCIAL_AUTH_AUTH0_KEY, return_to,
        )
        return HttpResponseRedirect(logout_url)


class AboutUs(View):
    template = "aboutus.html"
    def get(self, request):
        context = {}
        return render(self.request, self.template , context)


class Dashboard(View):
    @method_decorator(login_required)
    def get(self, request):
        snippets = Snippets.objects.filter(author = request.user)

        print(request.user)
        context = {
            'snippets': snippets,
            'page_title': 'dashboard'
        }
        return render(self.request, 'dashboard.html', context)


class Update(View):
    @method_decorator(login_required)
    def post(self, request):
        if request.method=='POST':
            raw = json.loads(request.body)

            try:
                obj = Snippets.objects.get(title = raw.get('title'))
                if raw.get('content') != None:
                    obj.content = raw.get('content')
                if raw.get('title') != None:
                    obj.title = raw.get('title')
                obj.author = str(request.user)
                obj.save()
            except Snippets.DoesNotExist:
                obj = Snippets(title = raw.get('title'), content = raw.get('content'), author =str(request.user))
                obj.save()            

            return JsonResponse({'status':'Success', 'msg': 'save successfully'})
        else:
            return JsonResponse({'status':'Fail', 'msg':'Not a valid request'})


class Delete(View):
    @method_decorator(login_required)
    def post(self, request):
        title = json.loads(request.body.decode("utf-8"))["link"] 
        snipp = get_object_or_404(Snippets, title = title)
        try:
            snipp.delete()
            return JsonResponse({"success": "Snippet is successfully deleted!" })
        except:
            return JsonResponse({"error": "Oops! Some error occured."})


class Features(View):
    def get(self, request):
        return render(request, 'features.html')


class Aboutus(View):
    def get(self, request):
        return render(request, 'aboutus.html')


class Segmentor(View):
    def get(self, request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.build(text))
        context = json.loads(nlps.process_props(text))
        sents = json.loads(nlps.get_sentences(text))

        params = {
            "message": "synonyms-net formed successfully!",
            "code": "api-v1",
            "sentences": sents["sentences"],
            "sent_count": sents["sent_count"],
            "data": response['data'],
            "mcw": context["mcw"],
            "pos": context["pos"],
            "summary": context["summary"],
            "status": 200
        }
        return JsonResponse(params)

class Dependency(View):
    def get(self ,request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.dependency_visualizer(text))
        params = {
            "dependency": response["dependency"]
        }
        return JsonResponse(params)

class Sentencer(View):
    def get(self, request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.get_sentences(text))
        params = {
            "sentences": response["sentences"]
        }
        return JsonResponse(params)

class Summary(View):
    def get(self, request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.generate_summary(text))
        params = {
            "summary": response["summary"]
        }
        return JsonResponse(params)

class Sentiment_Analysis(View):
    def get(self, request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.sentiment_analysis(text))
        params = {
            "sentiment": response["sentiment"]
        }
        return JsonResponse(params)

class PhraseMatcher(View):
    def get(self, request):
        text = request.GET.get('text')
        patterns = request.GET.get('patterns')

        nlps = OneNLP()
        response = json.loads(nlps.phrase_matcher(text, patterns))
        params = {
            "matched_phrases": response["matched_phrases"]
        }
        return JsonResponse(params)

class OppositeWord(View):
    def get(self, request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.oppositeWord(text))
        params = {
            "antonyms": response["antonyms"]
        }
        return JsonResponse(params)

class UsageOfWord(View):
    def get(self, request):
        text = request.GET.get('text')

        nlps = OneNLP()
        response = json.loads(nlps.usageOfWord(text))
        params = {
            "definitions": response["definitions"]
        }
        return JsonResponse(params)

onenlp_app/templates/aboutus.html
{% extends 'base.html' %}
{% load static %}


{% block navbar %}
<div class="navtabs swinginfes">
   <div class="navtab_wrapper">
      <svg xmlns="http://www.w3.org/2000/svg"  width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <rect x="4" y="4" width="6" height="6" rx="1" />
         <rect x="4" y="14" width="6" height="6" rx="1" />
         <rect x="14" y="14" width="6" height="6" rx="1" />
         <line x1="14" y1="7" x2="20" y2="7" />
         <line x1="17" y1="4" x2="17" y2="10" />
       </svg>
      <span onclick="window.location.href='{% url 'onenlp_app:dashboard' %}'">Dashboard</span>
   </div>
   <div id="prof" class="navtab_wrapper navactive">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <circle cx="12" cy="12" r="9" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(72 12 12)" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(144 12 12)" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(216 12 12)" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(288 12 12)" />
       </svg>
      <span onclick="window.location.href='{% url 'onenlp_app:aboutus' %}'">About</span>
   </div>
   {% if user.is_authenticated %}
   <div id="prof" class="navtab_wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <circle cx="12" cy="7" r="4" />
         <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
      </svg>
      <span onclick="window.location.href='{% url 'onenlp_app:logout' %}'">LogOut</span>
   </div>
   {% else %}
   <div id="prof" class="navtab_wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <circle cx="12" cy="7" r="4" />
         <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
      </svg>
      <span onclick="window.location.href='{{ login_url }}'">Login</span>
   </div>
   {% endif %}
</div>
{% endblock navbar %}


{% block content %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">

<style>
   .skills {
      color: #333;
      text-decoration: none;
   }
</style>
<div class="about_main">
   <div class="about-section" style="background: url('{% static 'img/pic.jpg' %}') no-repeat left;">
      <div class="inner-container">
        <h1>About OneNLP</h1>
        <p class="text">
         OneNLP is a modern <b>Natural processing language</b> IDE that enables you to perform all the NLP tasks visually with a good UI and yes , with ease!
         <br>

         Forgot all your traditional way of learning NLP , adopt a new clean and fast way , whether it's word tokenization or text manipulation , OneNLP is the name you wanna love to listen!
         <br>
         
         Student friendly, yes you need not to be a programmer , you may write your assignments , notes with all the correction and yes with all your Customizations.
         <br>
         
         No need of gooogling too much, for a silly synonym or antonym, <b>OneNLP</b> has got you covered.
        </p>
        <div class="skills">
          <span><a href="{% url 'onenlp_app:home' %}">IDE</a></span>
          <span><a href="{% url 'onenlp_app:dashboard' %}">Dashboard</a></span>
        </div>
      </div>
    </div>
</div>




{% endblock content %}

onenlp_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{% block title %} {% endblock %}</title>
      {% load static %}
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,700">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="https://unpkg.com/@yaireo/tagify/dist/tagify.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <script src="https://unpkg.com/@yaireo/tagify"></script>
      <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
   </head>
   <body>

      {% block navbar %}{% endblock navbar %}



      {% block content %}{% endblock %}

      
      <!-- ========== FOOTER ============ -->
    <div class="footer">
      <div class="footer-con">
         <div class="s-links" style="display: flex;align-items:center;">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-aperture" width="40" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fff" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
               <circle cx="12" cy="12" r="9" />
               <line x1="3.6" y1="15" x2="14.15" y2="15" />
               <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(72 12 12)" />
               <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(144 12 12)" />
               <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(216 12 12)" />
               <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(288 12 12)" />
             </svg>  <span style="color: #fff;" >OneNLP © 2021</span>
          </span>
          <a href="{% url 'onenlp_app:home' %}">Home</a>
            <a href="{% url 'onenlp_app:dashboard' %}">Dashboard</a>
            <a href="{% url 'onenlp_app:aboutus' %}">About us</a>
         </div>
         <div class="social">
            <svg onclick="window.location.href= 'https://github.com/prodexia/OneNLP'" xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
               <path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" />
            </svg>
         </div>
      </div>
   </div>
   </body>

   <script>
      function getCookie(name) {
         var cookieValue = null;
         if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
               var cookie = cookies[i].trim();
               if (cookie.substring(0, name.length + 1) == (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
               }
            }
         }
         return cookieValue;
      }
      
        var tabs = document.querySelectorAll(".navtab_wrapper")
        tabs.forEach((el) => {
            el.onclick = () => {
                $(el).siblings('div').removeClass('navactive').end().addClass('navactive');
            }
        })
   </script>
</html>

onenlp_app/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}


{% block navbar %}
<div class="navtabs swinginfes">
   <div class="navtab_wrapper navactive">
      <svg xmlns="http://www.w3.org/2000/svg"  width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <rect x="4" y="4" width="6" height="6" rx="1" />
         <rect x="4" y="14" width="6" height="6" rx="1" />
         <rect x="14" y="14" width="6" height="6" rx="1" />
         <line x1="14" y1="7" x2="20" y2="7" />
         <line x1="17" y1="4" x2="17" y2="10" />
       </svg>
      <span onclick="window.location.href='{% url 'onenlp_app:dashboard' %}'">Dashboard</span>
   </div>
   <div id="prof" class="navtab_wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <circle cx="12" cy="12" r="9" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(72 12 12)" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(144 12 12)" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(216 12 12)" />
         <line x1="3.6" y1="15" x2="14.15" y2="15" transform="rotate(288 12 12)" />
       </svg>
      <span onclick="window.location.href='{% url 'onenlp_app:aboutus' %}'">About</span>
   </div>
   {% if user.is_authenticated %}
   <div id="prof" class="navtab_wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <circle cx="12" cy="7" r="4" />
         <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
      </svg>
      <span onclick="window.location.href='{% url 'onenlp_app:logout' %}'">LogOut</span>
   </div>
   {% else %}
   <div id="prof" class="navtab_wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
         <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
         <circle cx="12" cy="7" r="4" />
         <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
      </svg>
      <span onclick="window.location.href='{{ login_url }}'">Login</span>
   </div>
   {% endif %}
</div>
{% endblock navbar %}


{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
   #app {
      min-height: 500px;
   }
</style>

<div style="margin-top: 56px;">
<main id="app" class="py-4 min-vh-100" style="background-color: rgb(246, 246, 246);">
   <div class="container">
      {% if not snippets %}
      <p style="text-align:center; margin-top: 90px;">You have 0 snippets , create one using <strong> + Create</strong> <br> button at the top/bottom bar.</p>
      <style>
         #table-view {
            display: none;
         }
      </style>
      {% endif %}
      <div id="table-view" class="dash-container">
         <div class="dash-wrapper">
            <table class="table table-hover">
               <thead class="theadzx-inverse">
                  <tr>
                     <th>Title</th>
                     <th>Content</th>
                     <th>Updated On</th>
                     <th>Actions</th>
                  </tr>
               </thead>
               <tbody>
                  {% for i in snippets %}
                  <tr>
                     <th scope="row">{{ i.title}}</th>
                     <td>{{ i.content|truncatechars:255 }}</td>
                     <td>{{ i.updated }}</td>
                     <td>
                        <svg xmlns="http://www.w3.org/2000/svg" class="del-btn" onclick="delete_link('{{ i.title }}')"  width="25" height="25" viewBox="0 0 24 24" stroke-width="1.5" stroke="#fd0061" fill="none" stroke-linecap="round" stroke-linejoin="round">
                           <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                           <rect x="4" y="4" width="16" height="16" rx="2" />
                           <path d="M10 10l4 4m0 -4l-4 4" />
                        </svg>

                        <svg xmlns="http://www.w3.org/2000/svg" title='{{ i.title }}' content='{{ i.content }}' onclick="load_snippet(this.getAttribute('title'), this.getAttribute('content'))" style="cursor: pointer;" width="25" height="25" viewBox="0 0 24 24" stroke-width="1.5" stroke="#6A27FF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                           <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                           <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5" />
                           <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5" />
                         </svg>
                     </td>
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>

      <style>
         .snippetbtn {
            display: flex;
            align-items: center;
            padding: 10px;
            border-radius: 10px;
            border: 0;
            margin: auto;
            color: #fff;
            cursor: pointer;
            background: #6A27FF;
            outline: none;
            transition: 1s all;
         }
      </style>
      <div class="text-center py-5">
            <button onclick="window.location.href='{% url 'onenlp_app:home' %}'" class="snippetbtn" type="button">
            Create New snippet +
            </button> 
      </div>
</main>
</div>
<script>
   function delete_link(link) {
      swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this action.",
            icon: "warning",
            buttons: true,
            dangerMode: true,
         })
         .then((willDelete) => {
            if (willDelete) {
   
               fetch("{% url 'onenlp_app:delete' %}", {
                     method: 'POST',
                     headers: {
                        'Content-Type': 'application/json',
                        "X-CSRFToken": getCookie("csrftoken"),
                     },
                     body: JSON.stringify({
                        link: link
                     }),
                  })
                  .then(response => response.text())
                  .then(data => {
                     swal("Your snippet has been deleted!", {
                        icon: "success",
                     });
                     window.location.href = window.location.href;
                  })
                  .catch((error) => {
                     toast(error);
                  });
   
            } else {
               swal("Your snippet is not deleted.");
            }
         });
   }

   function load_snippet(t, c) {
      var url = new URL(location.origin);
var search_params = url.searchParams;

// add "topic" parameter
search_params.set('title', t);
search_params.set('content', c);
url.search = search_params.toString();
var new_url = url.toString();

location.href = new_url;
}
</script>
{% endblock content %}